const cron = require('node-cron');
const { createLogger } = require('../../lib/logger');
const { createApp, listen } = require('../../lib/http');
const { createDb, query } = require('../../lib/db');
const { createRedis } = require('../../lib/redis');

const SERVICE = 'orchestrator';
const PORT = Number(process.env.PORT || 3000);
const MORNING_REPORT_CRON = process.env.MORNING_REPORT_CRON || '0 7 * * *';

const logger = createLogger(SERVICE);
const app = createApp({ service: SERVICE, logger });
const db = createDb(logger);
const redis = createRedis(logger);

app.get('/report', async (_req, res) => {
  const pending = await query(db, "SELECT COUNT(*)::int AS count FROM pending_actions WHERE status = 'pending'");
  res.json({ pendingCount: pending.rows[0]?.count || 0, generatedAt: new Date().toISOString() });
});

app.post('/dispatch/:agentId', async (req, res) => {
  const { agentId } = req.params;
  const payload = {
    agentId,
    trigger: req.body?.trigger || 'manual',
    context: req.body?.context || {},
    requestedAt: new Date().toISOString(),
  };

  if (redis) {
    await redis.publish('jobs:dispatch', JSON.stringify(payload));
  }

  logger.info(payload, 'dispatch request published');
  res.status(202).json({ ok: true, payload });
});

cron.schedule(MORNING_REPORT_CRON, async () => {
  logger.info({ cron: MORNING_REPORT_CRON }, 'morning report tick');

  const pending = await query(db, "SELECT COUNT(*)::int AS count FROM pending_actions WHERE status = 'pending'");
  const pendingCount = pending.rows[0]?.count || 0;

  if (db) {
    await query(
      db,
      `INSERT INTO morning_reports (date, report_text, pending_count)
       VALUES (CURRENT_DATE, $1, $2)
       ON CONFLICT (date) DO UPDATE SET report_text = EXCLUDED.report_text, pending_count = EXCLUDED.pending_count, sent_at = now()`,
      [`Morning report generated by ${SERVICE}`, pendingCount]
    );
  }

  if (redis) {
    await redis.publish('reports:morning', JSON.stringify({ pendingCount, ts: new Date().toISOString() }));
  }
});

listen(app, PORT, logger);
